version: 2.1

jobs:
  finalize_workflow:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          command: ./tools/install_myke.sh
      - run:
          command: myke mark_ci_ready

workflows:
  version: 2
  ci_cd:
    jobs:
      - finalize_workflow:
          filters:
            branches:
              ignore:
                - master

