name: CI
on:
  push:
    branches:
      - main

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        uses: ./.github/actions/build
