name: CI
on:
  push:
    branches:
      - main

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        uses: ./.github/actions/build
      - name: Tag for deployment
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: deployment-
          custom_tag: ${{ github.sha }}
