name: CI
on:
  push:
    branches:
      - main

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Build application
      #   uses: ./.github/actions/build
      - name: Push to production for deployment
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "production"
